// <auto-generated />
using System;
using ForjaDev.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForjaDev.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207154929_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("create_at_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("MemberId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Following", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberToFollowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_following");

                    b.HasIndex("FollowingMemberId");

                    b.HasIndex("MemberToFollowId", "FollowingMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_following_unique_relationship");

                    b.ToTable("following", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("slug");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("body");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("create_at_utc");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("likes_count");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MemberId");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.ValuesObject.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_like");

                    b.HasIndex("MemberId");

                    b.HasIndex("PostId");

                    b.ToTable("Like", (string)null);
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Comment", b =>
                {
                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Member", "Member")
                        .WithMany("Comments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_member");

                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Comment", "ParentComment")
                        .WithMany("SubComments")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("fk_comment_parent_comment");

                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_post");

                    b.Navigation("Member");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Following", b =>
                {
                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Member", "FollowingMember")
                        .WithMany()
                        .HasForeignKey("FollowingMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_following_target_member");

                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Member", "MemberToFollow")
                        .WithMany("Followings")
                        .HasForeignKey("MemberToFollowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_following_follower_member");

                    b.Navigation("FollowingMember");

                    b.Navigation("MemberToFollow");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Member", b =>
                {
                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ForjaDev.Domain.BackOffice.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ForjaDev.Domain.BackOffice.ValuesObject.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .HasMaxLength(150)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("role_title");

                            b1.HasKey("MemberId");

                            b1.ToTable("member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Post", b =>
                {
                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_post_category");

                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Member", "Member")
                        .WithMany("Posts")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_member");

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.User", b =>
                {
                    b.OwnsOne("ForjaDev.Domain.BackOffice.ValuesObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(220)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ForjaDev.Domain.BackOffice.ValuesObject.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.ValuesObject.Like", b =>
                {
                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_like_member");

                    b.HasOne("ForjaDev.Domain.BackOffice.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_like_post");

                    b.Navigation("Member");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Comment", b =>
                {
                    b.Navigation("SubComments");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Member", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Followings");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForjaDev.Domain.BackOffice.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
